# Generated by Django 3.1.5 on 2021-01-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='password2',
            field=models.CharField(max_length=10),
        ),
    ]
