# Generated by Django 3.1.5 on 2021-01-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_account_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_login',
        ),
    ]
